[2023-06-27T07:48:25.003+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_pnadc_data_new.get_mongodb_data manual__2023-06-27T07:48:21.542089+00:00 [queued]>
[2023-06-27T07:48:25.038+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_pnadc_data_new.get_mongodb_data manual__2023-06-27T07:48:21.542089+00:00 [queued]>
[2023-06-27T07:48:25.038+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-27T07:48:25.039+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-27T07:48:25.039+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-27T07:48:25.123+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): get_mongodb_data> on 2023-06-27 07:48:21.542089+00:00
[2023-06-27T07:48:25.132+0000] {standard_task_runner.py:55} INFO - Started process 4579 to run task
[2023-06-27T07:48:25.136+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_pnadc_data_new', 'get_mongodb_data', 'manual__2023-06-27T07:48:21.542089+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/get_pnadc_data_new.py', '--cfg-path', '/tmp/tmpjim9o_1j']
[2023-06-27T07:48:25.137+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask get_mongodb_data
[2023-06-27T07:48:25.283+0000] {task_command.py:389} INFO - Running <TaskInstance: get_pnadc_data_new.get_mongodb_data manual__2023-06-27T07:48:21.542089+00:00 [running]> on host 33a038a7552c
[2023-06-27T07:48:25.460+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_pnadc_data_new
AIRFLOW_CTX_TASK_ID=get_mongodb_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-27T07:48:21.542089+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-27T07:48:21.542089+00:00
[2023-06-27T07:48:25.473+0000] {base.py:73} INFO - Using connection ID 'mongodb_conn' for task execution.
[2023-06-27T07:52:14.931+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-06-27T07:52:14.945+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 4579. PIDs of all processes in the group: [4579]
[2023-06-27T07:52:14.946+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 4579
[2023-06-27T07:52:14.947+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-27T07:52:16.826+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4579, status='terminated', exitcode=0, started='07:48:24') (4579) terminated with exit code 0
