[2023-06-28T21:27:30.566+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_pnadc_data_new.transfer_rds_data_to_s3 manual__2023-06-28T17:25:44-04:00 [queued]>
[2023-06-28T21:27:30.579+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_pnadc_data_new.transfer_rds_data_to_s3 manual__2023-06-28T17:25:44-04:00 [queued]>
[2023-06-28T21:27:30.579+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T21:27:30.579+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-28T21:27:30.579+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T21:27:30.628+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): transfer_rds_data_to_s3> on 2023-06-28 21:25:44+00:00
[2023-06-28T21:27:30.649+0000] {standard_task_runner.py:55} INFO - Started process 2491 to run task
[2023-06-28T21:27:30.661+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_pnadc_data_new', 'transfer_rds_data_to_s3', 'manual__2023-06-28T17:25:44-04:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/get_pnadc_data_new.py', '--cfg-path', '/tmp/tmpluse_saa']
[2023-06-28T21:27:30.667+0000] {standard_task_runner.py:83} INFO - Job 291: Subtask transfer_rds_data_to_s3
[2023-06-28T21:27:30.810+0000] {task_command.py:389} INFO - Running <TaskInstance: get_pnadc_data_new.transfer_rds_data_to_s3 manual__2023-06-28T17:25:44-04:00 [running]> on host d9b032dfc97f
[2023-06-28T21:27:31.314+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_pnadc_data_new
AIRFLOW_CTX_TASK_ID=transfer_rds_data_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-06-28T21:25:44+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-28T17:25:44-04:00
[2023-06-28T21:27:31.326+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-06-28T21:27:31.326+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from login and password.
[2023-06-28T21:27:31.916+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-06-28T21:27:39.258+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-06-28T21:27:39.301+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=get_pnadc_data_new, task_id=transfer_rds_data_to_s3, execution_date=20230628T212544, start_date=20230628T212730, end_date=20230628T212739
[2023-06-28T21:27:39.406+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-06-28T21:27:39.427+0000] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
